version: '3'

services:

  postgres:
    image: postgres:11.3
    restart: unless-stopped
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: teamcity
      POSTGRES_PASSWORD: teamcity
      POSTGRES_DB: teamcity
      PGDATA: /var/lib/postgresql/data/pgdata

  teamcity-server:
    image: jetbrains/teamcity-server:2019.1
    restart: unless-stopped
    ports:
      - "8111:8111"
    volumes:
      - ./server/data:/data/teamcity_server/datadir"
      - ./server/logs:/opt/teamcity/logs
    links:
      - postgres
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:2019.1
    restart: unless-stopped
    privileged: true
    environment: 
      SERVER_URL: http://teamcity-server:8111
      DOCKER_IN_DOCKER: start
    volumes: 
      - ./agent-1/conf:/data/teamcity_agent/conf
      - ./agent-1/docker-volumes:/var/lib/docker
    links: 
      - teamcity-server
